### ISSUE TITLE
Add extra capabilities to Veracode Bash API

### ISSUE THREAD

**Issue by DinisCruz** [DinisCruz/veracode-api#13]
- [x] add alias `veracode-apps`  #15 
- [x] find ID for a particular project - done: `veracode-app-id` , 
- [x] Automatically create application when it is not there (to remove need to provide ID)
- [x] Delete an application - done: `veracode-delete-app` or `veracode-app-delete` #14 
- [x] Add ability to scan a file (jar or war) - done: `veracode-scan-file`
- [x] Get scan status 
- [x] List of app's builds - done: `veracode-app-builds`
- [x] Method to provide list of active scans #20
- [x] Check if there is a report for scan
- [x] Download report (pdf and xml)
- [x] Put downloaded report in repo, commit changes and push to repo
- [x] current scan status
- [x] test download report on Jenkins job (running at a regular interval)
- [ ] Add ability to scan a folder
- [ ] Add logging function #19
- [ ] Detect missing dependencies (after analysis)
